# Copyright (C) 2020-2024 Thomas Hess <thomas.hess@udo.edu>


"""
Declares the interface created by the PyQt5 resource compiler.
This is only used for type hinting.
"""

import typing

qt_version: typing.List[int] = ...
rcc_version: int = ...
qt_resource_data: bytes = ...
qt_resource_name: bytes = ...
qt_resource_struct: bytes = ...

def qCleanupResources() -> None: ...
def qInitResources() -> None: ...

del typing
