"project_id": "651100"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "mtg_proxy_printer/resources/translations/mtgproxyprinter_en-US.ts",
    "translation": "/mtg_proxy_printer/resources/translations/mtgproxyprinter_%locale%.ts",
  }
]
