"project_id": "651100"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "resources/translations/mtgproxyprinter_sources.ts",
    "translation": "resources/translations/mtgproxyprinter_%locale%.ts",
  }
]
