[tox]
min_version = 4.0

env_list =
    py3-unit_tests-{plain,compiled}-{windows, linux}
    py3-test_create_bundle-compiled-{windows, linux}

[testenv]
skip_install = True

platform =
    linux: linux
#    macos: darwin
    windows: win32

allowlist_externals =
    {toxinidir}{/}build{/}bundle_test{/}MTGProxyPrinter
    windows: {toxinidir}{/}scripts{/}clean_windows_build.bat
    linux: mv
    windows: move

deps =
    -r requirements.txt

build_deps =
    setuptools>=61

test_deps =
    {[testenv]build_deps}
    -r requirements-dev.txt

commands_pre =
    compiled: python {toxinidir}{/}scripts{/}compile_ui_files.py --full --purge-existing
    compiled: python {toxinidir}{/}scripts{/}compile_resources.py compile
    compiled-linux: mv {toxinidir}{/}mtg_proxy_printer{/}resources {toxinidir}{/}resources.bak
    compiled-windows: python -c "from pathlib import Path;__import__('shutil').move(Path('mtg_proxy_printer/resources'), Path('resources.bak'))"

commands_post =
    compiled-linux: mv {toxinidir}{/}resources.bak {toxinidir}{/}mtg_proxy_printer{/}resources
    compiled-windows: python -c "from pathlib import Path;__import__('shutil').move(Path('resources.bak'), Path('mtg_proxy_printer/resources'))"
    compiled: -python {toxinidir}{/}scripts{/}compile_ui_files.py --purge-existing
    compiled: python {toxinidir}{/}scripts{/}compile_resources.py clean


[testenv:py3-unit_tests-{plain,compiled}-{windows,linux}]

description =
    Runs the unit tests. On Linux, the GUI tests render off screen.
    factor plain loads UI/resources from source, factor compiled runs the resource and UI compilers first.

# Let Qt5 render offscreen, so that running tests don’t open windows or try to access the local system’s display
# This also prevents unwanted user interactions with the widgets under test.
# Offscreen rendering causes a segmentation fault on Windows, so simply show the GUI under test on Windows
set_env =
    compiled: MTGPROXYPRINTER_SKIP_RESOURCE_TESTS = 1
    linux: QT_QPA_PLATFORM = offscreen
    PYTHONDEVMODE = 1

deps =
    {[testenv]deps}
    -r requirements-dev.txt

commands =
    pytest tests

[testenv:py3-visible_unit_tests-{plain,compiled}]


# Runs the unit tests with the default Qt platform plugin,
# causing them to visibly spawn GUI windows for tests of view logic.
# Can be used to inspect the actions and GUI states manually.
# Not part of the environment list, so isn’t run automatically.

description =
    Runs the unit tests, always showing the GUI during GUI tests.
    factor plain loads UI/resources from source, factor compiled runs the resource and UI compilers first.

deps =
    {[testenv]deps}
    -r requirements-dev.txt

commands =
    pytest tests

# Pass DISPLAY, to allow rendering on screen. Also pass all other Qt-related environment variables,
# like QT_SCREEN_SCALE_FACTORS
pass_env =
    DISPLAY
    QT_*
    XDG_RUNTIME_DIR

set_env =
   compiled: MTGPROXYPRINTER_SKIP_RESOURCE_TESTS = 1
   PYTHONDEVMODE = 1


[testenv:py3-test_create_bundle-compiled-{windows, linux}]

description =
    Tests app freezing via cx_Freeze. Runs the built application with the --test-exit-on-launch flag,
    causing it to immediately exit.


deps =
    {[testenv]deps}
    -r requirements-package.txt

# Let Qt5 render offscreen, so that running tests don’t open windows or try to access the local system’s display
# This also prevents unwanted user interactions with the widgets under test
set_env =
    linux: QT_QPA_PLATFORM = offscreen
    PYTHONDEVMODE = 1

pass_env =
    XDG_RUNTIME_DIR

commands =
    python setup_cx_freeze.py build_exe --build-exe build{/}bundle_test
    windows: {toxinidir}{/}scripts{/}clean_windows_build.bat build{/}bundle_test
    {toxinidir}{/}build{/}bundle_test{/}MTGProxyPrinter --test-exit-on-launch



[testenv:py3-package-compiled-{windows,linux}]
description =
    Creates redistributable packages with build and cx_Freeze.

deps =
    {[testenv]deps}
    -r requirements-package.txt

commands =
    python -m build
    python setup_cx_freeze.py build_exe
    windows: {toxinidir}{/}scripts{/}clean_windows_build.bat
    windows: python setup_cx_freeze.py bdist_msi --skip-build
